///**
// * Autogenerated by Avro
// * 
// * DO NOT EDIT DIRECTLY
// */
//package LogModels;  
//import org.apache.avro.*;
//@SuppressWarnings("all")
////@org.apache.avro.specific.AvroGenerated
//public class CityLogs extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
//  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CityLogs\",\"namespace\":\"LogModels\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"logs\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
//  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
//  @Deprecated public java.lang.CharSequence name;
//  @Deprecated public java.util.List<java.lang.CharSequence> logs;
//
//  /**
//   * Default constructor.  Note that this does not initialize fields
//   * to their default values from the schema.  If that is desired then
//   * one should use <code>newBuilder()</code>. 
//   */
//  public CityLogs() {}
//
//  /**
//   * All-args constructor.
//   */
//  public CityLogs(java.lang.CharSequence name, java.util.List<java.lang.CharSequence> logs) {
//    this.name = name;
//    this.logs = logs;
//  }
//
//  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
//  // Used by DatumWriter.  Applications should not call. 
//  public java.lang.Object get(int field$) {
//    switch (field$) {
//    case 0: return name;
//    case 1: return logs;
//    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
//    }
//  }
//  // Used by DatumReader.  Applications should not call. 
//  @SuppressWarnings(value="unchecked")
//  public void put(int field$, java.lang.Object value$) {
//    switch (field$) {
//    case 0: name = (java.lang.CharSequence)value$; break;
//    case 1: logs = (java.util.List<java.lang.CharSequence>)value$; break;
//    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
//    }
//  }
//
//  /**
//   * Gets the value of the 'name' field.
//   */
//  public java.lang.CharSequence getName() {
//    return name;
//  }
//
//  /**
//   * Sets the value of the 'name' field.
//   * @param value the value to set.
//   */
//  public void setName(java.lang.CharSequence value) {
//    this.name = value;
//  }
//
//  /**
//   * Gets the value of the 'logs' field.
//   */
//  public java.util.List<java.lang.CharSequence> getLogs() {
//    return logs;
//  }
//
//  /**
//   * Sets the value of the 'logs' field.
//   * @param value the value to set.
//   */
//  public void setLogs(java.util.List<java.lang.CharSequence> value) {
//    this.logs = value;
//  }
//
//  /** Creates a new CityLogs RecordBuilder */
//  public static LogModels.CityLogs.Builder newBuilder() {
//    return new LogModels.CityLogs.Builder();
//  }
//  
//  /** Creates a new CityLogs RecordBuilder by copying an existing Builder */
//  public static LogModels.CityLogs.Builder newBuilder(LogModels.CityLogs.Builder other) {
//    return new LogModels.CityLogs.Builder(other);
//  }
//  
//  /** Creates a new CityLogs RecordBuilder by copying an existing CityLogs instance */
//  public static LogModels.CityLogs.Builder newBuilder(LogModels.CityLogs other) {
//    return new LogModels.CityLogs.Builder(other);
//  }
//  
//  /**
//   * RecordBuilder for CityLogs instances.
//   */
//  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CityLogs>
//    implements org.apache.avro.data.RecordBuilder<CityLogs> {
//
//    private java.lang.CharSequence name;
//    private java.util.List<java.lang.CharSequence> logs;
//
//    /** Creates a new Builder */
//    private Builder() {
//      super(LogModels.CityLogs.SCHEMA$);
//    }
//    
//    /** Creates a Builder by copying an existing Builder */
//    private Builder(LogModels.CityLogs.Builder other) {
//      super(other);
//      if (isValidValue(fields()[0], other.name)) {
//        this.name = data().deepCopy(fields()[0].schema(), other.name);
//        fieldSetFlags()[0] = true;
//      }
//      if (isValidValue(fields()[1], other.logs)) {
//        this.logs = data().deepCopy(fields()[1].schema(), other.logs);
//        fieldSetFlags()[1] = true;
//      }
//    }
//    
//    /** Creates a Builder by copying an existing CityLogs instance */
//    private Builder(LogModels.CityLogs other) {
//            super(LogModels.CityLogs.SCHEMA$);
//      if (isValidValue(fields()[0], other.name)) {
//        this.name = data().deepCopy(fields()[0].schema(), other.name);
//        fieldSetFlags()[0] = true;
//      }
//      if (isValidValue(fields()[1], other.logs)) {
//        this.logs = data().deepCopy(fields()[1].schema(), other.logs);
//        fieldSetFlags()[1] = true;
//      }
//    }
//
//    /** Gets the value of the 'name' field */
//    public java.lang.CharSequence getName() {
//      return name;
//    }
//    
//    /** Sets the value of the 'name' field */
//    public LogModels.CityLogs.Builder setName(java.lang.CharSequence value) {
//      validate(fields()[0], value);
//      this.name = value;
//      fieldSetFlags()[0] = true;
//      return this; 
//    }
//    
//    /** Checks whether the 'name' field has been set */
//    public boolean hasName() {
//      return fieldSetFlags()[0];
//    }
//    
//    /** Clears the value of the 'name' field */
//    public LogModels.CityLogs.Builder clearName() {
//      name = null;
//      fieldSetFlags()[0] = false;
//      return this;
//    }
//
//    /** Gets the value of the 'logs' field */
//    public java.util.List<java.lang.CharSequence> getLogs() {
//      return logs;
//    }
//    
//    /** Sets the value of the 'logs' field */
//    public LogModels.CityLogs.Builder setLogs(java.util.List<java.lang.CharSequence> value) {
//      validate(fields()[1], value);
//      this.logs = value;
//      fieldSetFlags()[1] = true;
//      return this; 
//    }
//    
//    /** Checks whether the 'logs' field has been set */
//    public boolean hasLogs() {
//      return fieldSetFlags()[1];
//    }
//    
//    /** Clears the value of the 'logs' field */
//    public LogModels.CityLogs.Builder clearLogs() {
//      logs = null;
//      fieldSetFlags()[1] = false;
//      return this;
//    }
//
//    @Override
//    public CityLogs build() {
//      try {
//        CityLogs record = new CityLogs();
//        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
//        record.logs = fieldSetFlags()[1] ? this.logs : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[1]);
//        return record;
//      } catch (Exception e) {
//        throw new org.apache.avro.AvroRuntimeException(e);
//      }
//    }
//  }
//}
